### ISSUE TITLE
Android LuaJIT

### ISSUE THREAD

**Issue by fritzy** [moai/moai-dev#1065]
In the develop branch:

If I change the flag in bin/build-android.sh to be `-DMOAI_LUAJIT=1 \`, ./build/build-android-armeabi/libmoai/third-party/luajit/luajit/src/libluajit.a appears to be built.

However, when running the host on an android machine, luajit appears to not be enabled.

``` lua
if (jit) then
    print "---------JIT--------"
else
    print "---------NOOOO--------"
end
```

This simple test prints the positive response with your 1.5.2 os x host, and the false response on my compiled android-host.

Thoughts?

**Comment by halfnelson** [comment]
because the libmoai.so is linked via a make file for ndk-build, it was difficult to get it to choose libluajit or  libluastatic. I think I have enough knowledge now to pass that setting through from gradle somehow. 

The plan originally was to have all modules on the linker line and based on the host-modules.h headers let the linker work out which were needed or which could be ignored. I can't do this for lua since libluajit and libluastatic implement the same interfaces and would fail linking.

I will probably add a "moaiUseLuajit" or something to the gradle settings along with the others and pass them through as a var to the make file and link accordingly.

It was lower priority since another dev had warned me about mysterious crashes on certain android devices (xperia, tab 3) that go away when luajit is swapped for lua (on android)
