### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by adamvillalobos** [moai/moai-dev#199]
-List 20 classes that need better documentation in source
-Add "TODO: doxygen" for all classes missing this
-List 30 classes to write wiki articles for
-Organize basics folder

**Comment by danadrew** [comment]
I've added the "TODO: doxygen" tag in every file that needs it now. After I finish the other tasks here I plan to do a more in-depth look at the comments we do have, because I found many errors in documentation and bugs in code when I was looking closely at them in just a few files. It was just taking too much time for now, I really needed to get all the TODOs in, so I'm going to come back to do that.

Going to compile the two lists now.

**Comment by danadrew** [comment]
Here are the lists I came up with.

**Improve the doxygen comments for:**
MOAIAction
MOAICamera
MOAIDeck
MOAIFont
MOAILayer
MOAIParticleSystem
MOAIParticleEmitter
MOAIParticleState
MOAIProp
MOAISim
MOAITextBox
MOAITextStyle
MOAITexture
MOAITransform
MOAIFileSystem
MOAIViewport
MOAIVertexBuffer
MOAIAnim
MOAITimer
MOAILogMgr

**Write wiki articles for:**
MOAIAnim
MOAICamera
MOAICameraFitter2D
MOAITextBox
MOAIFont
MOAITextStyle
MOAIFileSystem
MOAIParticleSystem
MOAITransform
MOAIPartition
All kinds of input
MOAILayer
MOAILayerBridge
MOAIAction
MOAITimer
MOAIEaseDriver
MOAIDeck
MOAIMesh
MOAIColor
MOAIDraw
MOAIShader
MOAIViewport
MOAIGrid
MOAILogMgr
MOAINode
MOAIPathFinder
MOAISim
MOAITexture
MOAIJsonParser
MOAIXmlParser
MOAIHttpTask
Untz
ZipFs

**Comment by danadrew** [comment]
I've reorganized the samples into many different folders now that describe the topic of the sample. I have a compiled list of the folders and their contents that I'll look into putting on the wiki.

I've completed all of my tasks in this issue so I'm going to pass it off to Patrick to do the doxygen comments and write the documentation.

**Comment by patrickmeehan** [comment]
Ongoign...
