### ISSUE TITLE
Modify run.sh to enable running with doubleclick

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#236]
http://getmoai.com/forums/requests-run-sh-t613/

**Comment by seanzipline** [comment]
I understand the problem - the run.sh scripts as provided will not function when double-clicked, because they don't change to the directory of the run.sh first (double-clicked shell scripts start off in the Users home folder, when run through Terminal).

The change as proposed adds a line to cd to the location of the run.sh itself, first, so that the MOAI resources can be found and the script can be run properly. Its a good solution and I suggest that all run.sh scripts be updated to do this. Also, it would be nice if there were some way to properly locate the moai binary, perhaps with an ENVIRONMENT variable..

**Comment by patrickmeehan** [comment]
trello
