### ISSUE TITLE
Crash in MOAIBitmapFontReader

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#386]
See sample in integration branch: samples / test / bitmap-font-reader
*Note: There are examples with two different fonts in the main.lua file. It should be clear which lines to comment/uncomment to switch between the two examples.

MOAIBitmapFontReader.loadPage () will crash if the third parameter is not a specific value. For the first example in the sample file, it will crash if the third parameter is anything but 16. For the second example, it will crash if the third parameter is anything but 8.

**Comment by patrickmeehan** [comment]
I'm pushing this bug off to next release.

The crash is happening because the numbers being ripped by the font reader don't match the font size being set in the text box. 16/72 works as does 8/144 because the number being passed to setTextSize () is 16 (the 72 for dpi is supplied as the default).

Moai _shouldn't_ crash, but the problem becomes how to fail gracefully. So... will get to this soon.

**Comment by patrickmeehan** [comment]
trello
