### ISSUE TITLE
Unclear listener interface MOAIEnvironment

### ISSUE THREAD

**Issue by DaanBroekhof** [moai/moai-dev#437]
I was digging into the code to see if I could get a callback/listener for screen-dimension changes on Windows, and stumbled upon 'MOAIEnvironment.setListener'.  The documentation on it was very sparse and seemingly inaccurate.

So the documentation and/or interface could use some improvement... (listing more information here so it's easier to find for others)
- setListener() was not listed as a function for MOAIEnvironment in the generated lua docs (probably doxygen not handling multiple inheritance right?)
- setListener() lists 'self', 'eventID ( number )' and 'callback' as arguments.
  - 'self ' can be filled as MOAIEnvironment, but strangely can also be any string.
  - 'eventID'  is something hard to find for MOAIEnvironment, not sure if it exists for this? Can use '0'
  - 'callback' is optional (?) and will have two call arguments: 'key' and 'value'
- 'screenHeight' and 'screenWidth' have been renamed to 'verticalResolution'  and 'horizontalResolution' , though not in the Lua documentation

So this works to get callbacks on window/screen resizes:

``` lua
MOAIEnvironment:setListener(0, function (key, value) print(key, value) end)
```

prints:

```
horizontalResolution    802
verticalResolution  600
```

**Comment by pygy** [comment]
As you've seen, it inherits from a MOAIGlobalClass, a class template which decorates MOAIGlobalEventSource, which provides the setListener() method...

From the Lua world, it should be seen as inheriting from GlobalEventSource, but the Doxygen parser doesn't understand the class template instantiation, and doesn't link to there. Furthermore, for some reason I've yet to elucidate, MOAIGlobalEventSource::_setListener(), which is documented in the source, doesn't appear in the SDK docs... Perhaps because it is a method documented in the header file? I'm not familiare with the current parser.

Reading the implementation of GlobalEventSource::_setListener, you could pass it a bicycle as first argument, it wouldn't complain. You could also pass `index` and `callback` as first and second args. It is actually a static method, its class is defined in the C++ source. It just ignores the first argument when it is not a number. 

Not sure why it's allowed to be called as if it were an instance method.

**Comment by DaanBroekhof** [comment]
Yup I got most of that from the source too.

In Lua MOAIEnvironment:setListener is nothing but syntactic sugar meaning MOAIEnvironment.setListener(MOAIEnvironment), so there is no 'instance' or not method characteristic. 

What I did find strange in that the 'self' and 'eventID' arguments, which seem to have no current function, have some requirements for the method to work. Passing 'nil' to them for instance will break the functionality of the function.

And aye there are some more strange things going on in the doxygen lua docs here and there...

**Comment by pygy** [comment]
The self is completely ignored, and since it is a static method, it shouldn't be allowed IMO.

The signature should be MOAIEnvironment.setListener(index,callback). 

Did you try to set different listeners at other indices? Perhaps it's possible to stack them?

**Comment by DaanBroekhof** [comment]
As far as saw when I tested, you can only set one listener, setting anything with any index will remove any previous listeners.

(and the 'index'/'eventID' must be 0, or you won't get any callbacks at all)

Seems like MOAIEnvironment has no separate listener event 'ids' (no constants defined for that either...)

Ideally you would want to register listeners for specific environment properties by name (string, not number), but that wouldn't work with the current setListener() signature.
