### ISSUE TITLE
MOAITextBox's seekLoc() speed is not same as other props.

### ISSUE THREAD

**Issue by sakim** [moai/moai-dev#451]
While I'm moving multiple props including MOAITextBox with seekLoc(), text boxes are moving slow than other props.

Because MOAITextBox itself is a prop, it should move same speed as other props.

Current workaround is just set textboxes' parent to other prop. This is quite annoying.

I'm working on master branch.

**Comment by patrickmeehan** [comment]
Just tried this out. They seem to be the same speed.

I'm wondering if the problem you are having is that you are using a MOAIProp2D instead of a MOAIProp. MOAIProp2D is a dummy class with a different interface meant for backward compatibility. It's seekLoc method takes ( X, Y, time, curve). MOAIProp takes (X, Y, Z, time, curve).

MOAIProp2D will be deprecated in a future release. Also, there is no equivalent MOAITextBox2D.

Just try passing a '0' for the 'Z' parameter and you should see the seek play at the same speed as everything else.
