### ISSUE TITLE
Expose basic cross-platform native pop-up and alerts UI

### ISSUE THREAD

**Issue by patrickmeehan** [moai/moai-dev#49]
Some platforms support basic, native pop-ups for simple dialogues and alerts. To the extent these ad hocs and alerts can be supported across all platforms, we should expose them. (The intent here is _not_ to provide a full featured native UI wrapper. Just alerts, pop-ups and simple dialogues that can be supported across _all_ platforms.)

**Comment by seanzipline** [comment]
I assigned this back to you because this is an issue likely to be connected to the cleanup of MOAIApp, etc. I have unified the showDialog APIs across Android and iPhone, but this work item was meant to be something larger - something I'm not even sure is part of 1.0 (TBD when you work on the MOAIApp, etc. cleanup).

**Comment by patrickmeehan** [comment]
trello
