### ISSUE TITLE
Figure out a documentation solution for Lua modules

### ISSUE THREAD

**Issue by seanzipline** [moai/moai-dev#81]

**Comment by pygy** [comment]
I guess that this issue is about the API, then...

Would you like to crowdsource it as well?

**Comment by seanzipline** [comment]
This is specifically for the lua-modules that we ship as part of the SDK - apsalar, tapjoy, url and util. They are, as of now, completely undocumented and we need to find a way to get that done. We've discussed either parsing the Lua (or looking for a 3rd party Lua documentation generator) or creating dummy header files for these and then letting our doxygen parser do the work. The downside of the latter is that we have to keep the header files in sync with the Lua, which sucks.

If you have any other suggestions, we're all ears - thanks!

**Comment by pygy** [comment]
Does your Doxygen parser require well formed C++ files?

If not you could wrap the Doxygen comments in Lua block comments.

Otherwise, there's luadoc, or you could write your own parser for doxygen-like comment systems. I have an almost working lpeg-based ghetto parser. When done, It should parse doxygen comments followed by a class declaration or a method signature. It ignores everything else. I may also make it parse the `luaL_regTable` definition to ensure there's no typo.

**Comment by seanzipline** [comment]
Not sure. That's worth a try.

**Comment by adamvillalobos** [comment]
Going to use dummy C header files for Lua modules.
