### ISSUE TITLE
Chrome host does not work.

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#829]
Chrome host does not work.
It will should be able to operate with Cmake. 
Should the SDLHost?

**Comment by halfnelson** [comment]
I am not sure nacl was ever part of the cmake build process. It should be doable, but IMHO it is a dead technology, replaced by either emscripten or PNacl. If we were to support it,  I would rewrite support as PNacl so that it can run on chrome without installing via app store. The emscripten port works for me and runs on both firefox and chrome (and I guess opera)

**Comment by makotok** [comment]
Thank you for your comment. 
I also agree to HTML Host.

**Comment by JDaance** [comment]
Chrome host is terribly outdated, it's not possible to download the SDK needed to use it anymore. I used it previously but replaced it with emscripten. I vote to remove it from the repo to keep it clean.
