### ISSUE TITLE
Enable the travis-ci

### ISSUE THREAD

**Issue by makotok** [moai/moai-dev#844]
I want to correspond to the travis-ci the moai-dev repository. 
However, this operation requires administrator privileges. 

Is it possible to enable someone?

https://travis-ci.org/

**Comment by halfnelson** [comment]
Once you have it setup and if you want automatic osx builds, you will need create a branch of master called travis-osx and change the .travis.yml file to match the one on moaiforge (change c to objective-c and change ci-linux.sh to ci-osx.sh)

To trigger the osx builds I have the main ci-linux.sh checking out travis-osx and merging in master, then pushing to github to trigger a build (with the different .travis.yml found on travis-osx branch), you will need to change the repository that this pushes to in your ci-linux.sh file. 

You will see that the .travis.yml on the master branch has a secure global env. You will need to generate one of these by following directions here: https://github.com/moaiforge/moai-sdk/wiki/Setup-Travis-with-write-access-to-github

Hope that helps

**Comment by halfnelson** [comment]
any luck with this?

**Comment by makotok** [comment]
Thank you for information. 
I was not able to support it, too busy. 

I try.

**Comment by makotok** [comment]
I can not be still. No permissions to me.

```
makoto-air:~ mkinoshita$ curl -X POST -u moai-ci -H "Content-Type: application/json" -d "{\"scopes\":[\"public_repo\"],\"note\":\"token for pushing from travis\"}" https://api.github.com/authorizations
Enter host password for user 'moai-ci':
{
  "message": "Bad credentials",
  "documentation_url": "http://developer.github.com/v3"
}
```

**Comment by makotok** [comment]
I can not create a new user.

**Comment by halfnelson** [comment]
The moai-ci user should be created by just creating an account the normal
way with github (ie sign up via the web site). I can do this for you if you
want.
You will then need to get moai-ci added as a collaborator (
https://github.com/moai/moai-dev/settings/collaboration)

Once you have done the above steps, the curl command will allow you to
create a token for the moai-ci user.

You could just create a token for yourself (makoto) instead of moai-ci, but
if somebody gets that token, they can commit to ALL of your repositories.
This is why it is suggested that you make a dedicated user just for this.

Let me know if I can help more

**Comment by halfnelson** [comment]
if you log into github as the moai-ci user you created, and visit: 
https://github.com/settings/tokens/new

you can create a token there and give it public:repo access, you can then do the rest of the steps.

**Comment by halfnelson** [comment]
uses jenkins now
